app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

api:
    resource: "@ApiBundle/Resources/config/routing.yml"
    host: api.hereissheep.dev
#    prefix: /api

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/docs

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"