services:
  # This is essential for ParamConverter when working with MongoDB
  doctrine_mongo_db_param_converter:
    class: Sensio\Bundle\FrameworkExtraBundle\Request\ParamConverter\DoctrineParamConverter
    arguments: [@doctrine_mongodb]
    tags:
      - {name: request.param_converter, converter: doctrine.odm}