api_products:
    type:     rest
    resource: "@ApiBundle/Resources/config/products_routes.yml"

api_categories:
    type:     rest
    resource: "@ApiBundle/Resources/config/categories_routes.yml"

api_users:
    type:     rest
    resource: "@ApiBundle/Resources/config/user_routes.yml"